tap "git-duet/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "theseal/ssh-askpass"
tap "universal-ctags/universal-ctags"
tap "caskroom/cask"

cask "google-chrome"
cask "flycut"
cask "shiftit"
cask "flux"
cask "evernote"
cask "docker"
cask "virtualbox"

brew "python", link: false
brew "ansible"
brew "node"
brew "autocode"
brew "autojump"
brew "gnu-sed"
brew "tmux"
brew "byobu"
brew "cfssl"
brew "go"
brew "dep"
brew "direnv"
brew "dos2unix"
brew "fzf"
brew "git"
brew "gnupg"
brew "grunt-cli"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "k9s"
brew "neovim"
brew "pipenv"
brew "pstree"
brew "pyenv"
brew "qt"
brew "rbenv-binstubs"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "watch"
brew "wget"
brew "wireshark", link: false
brew "yarn"
brew "z"
brew "kubectx"
brew "kind"
brew "dockerize"
brew "kube-ps1"

brew "git-duet/tap/git-duet"
brew "theseal/ssh-askpass/ssh-askpass"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "bat"
