export PATH="/usr/local/bin:$PATH"

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
export BASH_IT_THEME="guillermo"
# export BASH_IT_THEME="bobby"

# Setup LaTex
eval "$(/usr/libexec/path_helper)"

# Load Bash It
source $BASH_IT/bash_it.sh

source ~/.bashrc

[[ -s "/Users/guillermo/.gvm/scripts/gvm" ]] && source "/Users/guillermo/.gvm/scripts/gvm"
