export PATH="/usr/local/bin:$PATH"

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
export BASH_IT_THEME="guillermo"

# Load Bash It
source $BASH_IT/bash_it.sh

source ~/.bashrc
