# Setup arrow up and arrow down
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Setup aliases
source ~/.aliases

# Setup fuzzy search 
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Setup Go Path
export PATH=$PATH:/usr/local/opt/go/libexec/bin:~/go/bin
export GOPATH=$HOME/go

# Setup NeoVim
if [ ! -L "$HOME/.config/nvim" ]; then
    ln -s "$HOME/.vim" "$HOME/.config/nvim"
fi
